 <?php

    class EmployeeFacade {

        // Private Fields


        // Default Constructor


        // Methods
        function create_employee_record(){

        }

        function read_employee_record(){
            
        }

        function update_employee_record(){
            
        }

        function delete_employee_record(){
            
        }

        // Getters
        function get_name(){
            return $this->name;
        }

        // Setters
        function set_name($name) {
            $this->name = $name;
        }

    }

?> 